# Generated by Django 5.1.3 on 2024-11-11 09:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(max_length=255)),
                ('certificate_id', models.CharField(max_length=100, unique=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='certificates/logos/')),
                ('signature_text', models.CharField(default='Authorized Signature', max_length=255)),
                ('hash_value', models.CharField(blank=True, max_length=64, null=True)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='certificates/qrcodes/')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='certificates/signatures/')),
                ('note', models.TextField(default='This is an official certificate.')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/pdfs/')),
            ],
        ),
    ]
