# Generated by Django 5.1.3 on 2024-11-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_alter_certificate_certificate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='note',
            field=models.TextField(default='This certificate serves as a testament to the dedication, knowledge, and achievements of the holder. It is a mark of excellence, symbolizing the hard work and commitment demonstrated throughout the course of their journey. Congratulations on reaching this milestone.'),
        ),
    ]
